/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as InviteAcceptRouteImport } from './routes/invite/accept'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups/index'
import { Route as AuthenticatedFormsIndexRouteImport } from './routes/_authenticated/forms/index'
import { Route as AuthenticatedInstancesReadableIdRouteImport } from './routes/_authenticated/instances/$readableId'
import { Route as AuthenticatedGroupsGroupIdRouteImport } from './routes/_authenticated/groups/$groupId'
import { Route as AuthenticatedFormsNewRouteImport } from './routes/_authenticated/forms/new'
import { Route as AuthenticatedFormsTemplateIdRouteRouteImport } from './routes/_authenticated/forms/$templateId/route'
import { Route as AuthenticatedFormsTemplateIdIndexRouteImport } from './routes/_authenticated/forms/$templateId/index'
import { Route as AuthenticatedFormsTemplateIdEditRouteImport } from './routes/_authenticated/forms/$templateId/edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormsIndexRoute = AuthenticatedFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstancesReadableIdRoute =
  AuthenticatedInstancesReadableIdRouteImport.update({
    id: '/instances/$readableId',
    path: '/instances/$readableId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsGroupIdRoute =
  AuthenticatedGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormsNewRoute = AuthenticatedFormsNewRouteImport.update({
  id: '/forms/new',
  path: '/forms/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormsTemplateIdRouteRoute =
  AuthenticatedFormsTemplateIdRouteRouteImport.update({
    id: '/forms/$templateId',
    path: '/forms/$templateId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormsTemplateIdIndexRoute =
  AuthenticatedFormsTemplateIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFormsTemplateIdRouteRoute,
  } as any)
const AuthenticatedFormsTemplateIdEditRoute =
  AuthenticatedFormsTemplateIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedFormsTemplateIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/forms/$templateId': typeof AuthenticatedFormsTemplateIdRouteRouteWithChildren
  '/forms/new': typeof AuthenticatedFormsNewRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/instances/$readableId': typeof AuthenticatedInstancesReadableIdRoute
  '/forms/': typeof AuthenticatedFormsIndexRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/forms/$templateId/edit': typeof AuthenticatedFormsTemplateIdEditRoute
  '/forms/$templateId/': typeof AuthenticatedFormsTemplateIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/': typeof AuthenticatedIndexRoute
  '/forms/new': typeof AuthenticatedFormsNewRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/instances/$readableId': typeof AuthenticatedInstancesReadableIdRoute
  '/forms': typeof AuthenticatedFormsIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/forms/$templateId/edit': typeof AuthenticatedFormsTemplateIdEditRoute
  '/forms/$templateId': typeof AuthenticatedFormsTemplateIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/forms/$templateId': typeof AuthenticatedFormsTemplateIdRouteRouteWithChildren
  '/_authenticated/forms/new': typeof AuthenticatedFormsNewRoute
  '/_authenticated/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/_authenticated/instances/$readableId': typeof AuthenticatedInstancesReadableIdRoute
  '/_authenticated/forms/': typeof AuthenticatedFormsIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/forms/$templateId/edit': typeof AuthenticatedFormsTemplateIdEditRoute
  '/_authenticated/forms/$templateId/': typeof AuthenticatedFormsTemplateIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/invite/accept'
    | '/forms/$templateId'
    | '/forms/new'
    | '/groups/$groupId'
    | '/instances/$readableId'
    | '/forms/'
    | '/groups/'
    | '/reports/'
    | '/forms/$templateId/edit'
    | '/forms/$templateId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/invite/accept'
    | '/'
    | '/forms/new'
    | '/groups/$groupId'
    | '/instances/$readableId'
    | '/forms'
    | '/groups'
    | '/reports'
    | '/forms/$templateId/edit'
    | '/forms/$templateId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/settings'
    | '/invite/accept'
    | '/_authenticated/'
    | '/_authenticated/forms/$templateId'
    | '/_authenticated/forms/new'
    | '/_authenticated/groups/$groupId'
    | '/_authenticated/instances/$readableId'
    | '/_authenticated/forms/'
    | '/_authenticated/groups/'
    | '/_authenticated/reports/'
    | '/_authenticated/forms/$templateId/edit'
    | '/_authenticated/forms/$templateId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InviteAcceptRoute: typeof InviteAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forms/': {
      id: '/_authenticated/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof AuthenticatedFormsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/$readableId': {
      id: '/_authenticated/instances/$readableId'
      path: '/instances/$readableId'
      fullPath: '/instances/$readableId'
      preLoaderRoute: typeof AuthenticatedInstancesReadableIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/$groupId': {
      id: '/_authenticated/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forms/new': {
      id: '/_authenticated/forms/new'
      path: '/forms/new'
      fullPath: '/forms/new'
      preLoaderRoute: typeof AuthenticatedFormsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forms/$templateId': {
      id: '/_authenticated/forms/$templateId'
      path: '/forms/$templateId'
      fullPath: '/forms/$templateId'
      preLoaderRoute: typeof AuthenticatedFormsTemplateIdRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forms/$templateId/': {
      id: '/_authenticated/forms/$templateId/'
      path: '/'
      fullPath: '/forms/$templateId/'
      preLoaderRoute: typeof AuthenticatedFormsTemplateIdIndexRouteImport
      parentRoute: typeof AuthenticatedFormsTemplateIdRouteRoute
    }
    '/_authenticated/forms/$templateId/edit': {
      id: '/_authenticated/forms/$templateId/edit'
      path: '/edit'
      fullPath: '/forms/$templateId/edit'
      preLoaderRoute: typeof AuthenticatedFormsTemplateIdEditRouteImport
      parentRoute: typeof AuthenticatedFormsTemplateIdRouteRoute
    }
  }
}

interface AuthenticatedFormsTemplateIdRouteRouteChildren {
  AuthenticatedFormsTemplateIdEditRoute: typeof AuthenticatedFormsTemplateIdEditRoute
  AuthenticatedFormsTemplateIdIndexRoute: typeof AuthenticatedFormsTemplateIdIndexRoute
}

const AuthenticatedFormsTemplateIdRouteRouteChildren: AuthenticatedFormsTemplateIdRouteRouteChildren =
  {
    AuthenticatedFormsTemplateIdEditRoute:
      AuthenticatedFormsTemplateIdEditRoute,
    AuthenticatedFormsTemplateIdIndexRoute:
      AuthenticatedFormsTemplateIdIndexRoute,
  }

const AuthenticatedFormsTemplateIdRouteRouteWithChildren =
  AuthenticatedFormsTemplateIdRouteRoute._addFileChildren(
    AuthenticatedFormsTemplateIdRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFormsTemplateIdRouteRoute: typeof AuthenticatedFormsTemplateIdRouteRouteWithChildren
  AuthenticatedFormsNewRoute: typeof AuthenticatedFormsNewRoute
  AuthenticatedGroupsGroupIdRoute: typeof AuthenticatedGroupsGroupIdRoute
  AuthenticatedInstancesReadableIdRoute: typeof AuthenticatedInstancesReadableIdRoute
  AuthenticatedFormsIndexRoute: typeof AuthenticatedFormsIndexRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFormsTemplateIdRouteRoute:
    AuthenticatedFormsTemplateIdRouteRouteWithChildren,
  AuthenticatedFormsNewRoute: AuthenticatedFormsNewRoute,
  AuthenticatedGroupsGroupIdRoute: AuthenticatedGroupsGroupIdRoute,
  AuthenticatedInstancesReadableIdRoute: AuthenticatedInstancesReadableIdRoute,
  AuthenticatedFormsIndexRoute: AuthenticatedFormsIndexRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InviteAcceptRoute: InviteAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
