-- Change report_templates.auto_generate default to true so new templates
-- are auto-generated by default. Existing templates are not changed.

ALTER TABLE public.report_templates
  ALTER COLUMN auto_generate SET DEFAULT true;
